apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  ports:
  - port: {{ .Values.service.redisPort }}
    name: redis
  - port: {{ .Values.service.mysqlPort }}
    name: mysql
  selector:
    app: {{ .Chart.Name }}
{{ if .Values.ingress.enabled }}
  type: ClusterIP
{{ else }}
  type: NodePort
{{ end }}